### ISSUE TITLE
GPU brute force NN

### ISSUE THREAD

**Issue by iceblue25** [KristofferC/NearestNeighbors.jl#10]
Any plans to support GPU based brute force NN using https://github.com/JuliaGPU ?

Can be a good solution for high dimensional data.

http://nichol.as/papers/Garcia/Fast%20k%20nearest%20neighbor%20search%20using.pdf

**Comment by KristofferC** [comment]
That's a cool idea. I did some GPU programming for my bachelor thesis http://publications.lib.chalmers.se/records/fulltext/144105.pdf so I know at least a little about it.

This is the code used in the paper: https://github.com/vincentfpgarcia/kNN-CUDA but it looks like the license is incompatible with the MIT license used in this paper.

The roadmap to implementing this could be to follow the steps in section 2.3 of http://www.vincentgarcia.org/data/Garcia_2010_ICIP.pdf

I've used CUBLAS.jl before and it works quite well. 

Do you plan on putting any work towards this yourself?

Another reference:

http://web.cs.ucdavis.edu/~amenta/pubs/bfknn.pdf

**Comment by KristofferC** [comment]
I did some small steps towards this, see: https://gist.github.com/KristofferC/2d476ac6022169c8852f

As a first step this is supposed to compute the distance matrix but there is a bug in the columsq kernel so the results in the vector are not in the correct order.

It is also a bit inefficient since it is using the CUBLAS rank 1 update `ger` when a custom kernel would theoretically be more effective since the 1-vectors are then not needed.

Have to go but thought I would post this here if anyone wants to run with it.

**Comment by KristofferC** [comment]
Update at: https://gist.github.com/KristofferC/96c8d3ce8d7fa29f0441

This now produces the correct distance matrix and seems to be ~2x faster than the cpu on my computer.

```jl
julia> @time pairwise(SqEuclidean(), datap, queryp);
  0.252798 seconds (22.75 k allocations: 367.284 MB, 20.10% gc time)

julia> @time pairwise_GPU(data, query);
  0.116787 seconds (1.14 k allocations: 366.261 MB, 20.23% gc time)
```

I'm not freeing any gpu memory though so the gpu runs out of memory after some calls. I also had to rewrite some CUBLAS functions to accept PitchedArrays because I thought that was what you were supposed to do for matrices... 

What is needed now is a way to do the "nth-element" sort in cuda. http://stackoverflow.com/questions/8648968/algorithm-in-thrust-cudpp-to-find-kth-smallest-element says it doesnt exist yet.

**Comment by iceblue25** [comment]
To be honest, I would love to work on this but unfortunately the organization I work for needs to go through layers of management and lawyers to get permission and justification to release code. Also, MIT license might not be allowed.

Also, w.r.t to your timings does the GPU include copying to GPU memory? For example, an equivalent of build_tree is to copy the training data points to gpu memory. What is the speedup excluding memory copies? What is your gpu card? (tflops? I think state of the art do 17 tflops at this point)

**Comment by iceblue25** [comment]
Also, what is the speed on finding the kth element on cpu. Might be negligible. You need a memory copy and find kth element which is linear O(N)

**Comment by iceblue25** [comment]
Thanks for the links regards your past GPU. Really cool stuff I am having a deeper look.

**Comment by KristofferC** [comment]
Well you can "work" on your spare time like the rest of us ;)

My GPU is a Geforce GTx 770 which has ~ 3.21 tflops theoretical max so not really state of the art hehe.

I updated a branch to do some GPU benchmarking. https://github.com/KristofferC/NearestNeighbors.jl/compare/kc/gpu?expand=1

It only does a distance matrix yet because I don't know the best way to do the n-th element sort on each column in parallel. I'll check doing the extraction on cpu later. I will also check how much of the time is spent in transferring memory to the GPU.

Btw. I don't like the benchmarks in your linked paper. They compare their optimized brute force solution to for example the ANN library for high enough dimensions where a tree structure performs worse than brute search. They should instead have compared with something that does the equivalent optimizations on the CPU like [Distances.jl](https://github.com/JuliaStats/Distances.jl) does with their `pairwise` function. This performs 300 times better than the naive brute force (that ANN uses).

**Comment by KristofferC** [comment]
Did some more updates at https://github.com/KristofferC/NearestNeighbors.jl/compare/kc/gpu?expand=1

So far the GPU results are not very impressive so I don't see this providing a dramatic speed up over a properly coded CPU implementation.

If anyone has a state of the art GPU and could run the benchmark in that branch it would be interesting to see the results.

Here are mine for 10 000 points in 50 dimensions querying with 10 000 other points.

```
Type: Float32
CPU
  0.226966 seconds (33 allocations: 381.547 MB, 1.05% gc time)
CPU + ger!
  0.269377 seconds (7.96 k allocations: 488.833 KB)
GPU + custom kernel
  0.229034 seconds (31.25 k allocations: 382.877 MB, 4.60% gc time)
GPU + ger!
  0.225263 seconds (13.16 k allocations: 382.052 MB, 15.07% gc time)

Type: Float64
CPU
  0.467601 seconds (33 allocations: 763.093 MB, 6.87% gc time)
CPU + ger!
  0.517848 seconds (38 allocations: 313.781 KB)
GPU + custom kernel
  0.377023 seconds (839 allocations: 762.972 MB, 2.71% gc time)
GPU + ger!
  0.367367 seconds (861 allocations: 762.973 MB, 27.94% gc time)
```

**Comment by iceblue25** [comment]
Interesting repo about gpu-benchmarking in julia for matrix multiplication and other operations


https://github.com/ranjanan/GPU-benchmarking

Seems gpu type and data transfer are important.
