### ISSUE TITLE
`inrange` returning indices ordered by distance

### ISSUE THREAD

**Issue by juliohm** [KristofferC/NearestNeighbors.jl#86]
I was using the option `sortres` in `inrange` thinking that it was ordering the indices from smallest to largest distance. I then realized, by reading the source code, that the ordering is on the indices found.

Is there any efficient method for getting a list of indices ordered by distance? That would be useful.

**Comment by KristofferC** [comment]
See:

> Note that for performance reasons the distances are not returned.

`inrange` is made fast is by not computing the distances when that is not needed to know if the point is in range or not. You would need to call the distance function on all points yourself afterwards since that is not any information we have stored anywhere.

FWIW, the `sortres` option for `inrange` should probably be removed, it doesn't do anything useful.

**Comment by juliohm** [comment]
> FWIW, the `sortres` option for `inrange` should probably be removed, it doesn't really do anything useful.

I agree, I thought the option was doing the sort by distance. I would just remove it to avoid future confusion by other users.

So the tree search method doesn't provide any side effects like order by distance for free? I will call `inrange`, and then calculate the distances if that is needed. Thanks.

**Comment by KristofferC** [comment]
> So the tree search method doesn't provide any side effects like order by distance for free?

For `knn`, yes but for `in_range` it is possible to determine that all points in a branch of the tree are in range without having to compute the distance for all points in that branch.
